### PR TITLE
build(appimage): upgrade to Python 3.8.18

### PR DESCRIPTION
**Pull request by tiborsimko**
Fixes AppImage building procedure by upgrading to Python 3.8.18.

### CODE REVIEW

**Review by giuseppe-steduto — APPROVED** [review]
LGTM!
A small note: I had to run the script as superuser in order to have the permission to complete the AppImage build process successfully. Is this intended behavior?

**Comment by tiborsimko** [comment]
>  had to run the script as superuser in order to have the permission to complete the AppImage build process successfully. Is this intended behavior?

Hmm, I'm running it as a regular use. Perhaps we can see IRL about the troubles you've met?

**Comment by tiborsimko** [comment]
> Hmm, I'm running it as a regular use. Perhaps we can see IRL about the troubles you've met?

I managed to reproduce a runtime error: it happens when I launch this script whilst being in the `reana` virtual environment. However, when you `deactivate` first, and use the vanilla operating system Python, then the script runs fine. Perhaps you tried it out whilst being in the `reana` venv?

**Review by mdonadoni — APPROVED** [review]
Works well after the latest changes (outside the `reana` venv)

**Pull request merged**
