### PR TITLE
cli: implement list --shared argument

### LINKED ISSUE #687: cli: implement `list --shared` argument

### PR DESCRIPTION
**Pull request by DaanRosendal**
Adds new `--shared`, `--shared-by`, and `--shared-with` arguments to the
`list` CLI command to display workflows along with their sharing
information.

Closes #687

### CODE REVIEW

**Comment by mdonadoni** [comment]
Latest version before rebase:  c429f3e 

Still many comments to be addressed

**Comment by mdonadoni** [comment]
Ready to be reviewed, squashed and merged. CI should pass after a release of r-commons

**Review by tiborsimko — APPROVED** [review]
Works nicely :+1: with

```
- r-client #692
- r-client-go #153
- r-ui #375
- r-server #658
- r-workflow-controller #552
- r-commons #429
- r-db #216
```

Kept separate commits, rephrased commit log headlines, bumped pytest-reana dependency.

**Comment by tiborsimko** [comment]
> Kept separate commits, rephrased commit log headlines, bumped pytest-reana dependency.

Also had to add a weird multi-dependency dance in `setup.py` due to not-yet-releasable reana-commons package so that CI  would pass, as well as  fixed the formatting of two CLI command examples in the help output so that it would match documentation (that needed some indentation fixes).

**Pull request merged**
