### PR TITLE
cli: change in output_format flag

### PR DESCRIPTION
**Pull request by dinosk**
* Changes the `--output-format,  -of` flag to `--json`

(Closes https://github.com/reanahub/reana-client/issues/74)

Signed-off-by: Dinos Kousidis <konstantinos.kousidis@cern.ch>

### CODE REVIEW

**Comment by dinosk** [comment]
@hjhsalo yes I agree with @tiborsimko in https://github.com/reanahub/reana-client/issues/74, json2yaml is an easy option. What do you think?

**Comment by hjhsalo** [comment]
Well, I would have it since it isn't (or at least doesn't seem to be) affecting anything else than output, but 1) I don't have strong arguments why it should be kept, 2) I usually lose debates, so let's drop it :)

**Comment by dinosk** [comment]
@hjhsalo :D

**Comment by diegodelemos** [comment]
We have a miss match between what `reana-server` API returns and `reana-client * --json` returns. For instance, `id` in the API response and `UUID` written by `tablib` (as configured [here](https://github.com/reanahub/reana-client/pull/82/files#diff-19bed1e7334d00a24f059e517c55f01dR254)):

```json
$ diff -y <(curl -s "$REANA_SERVER_URL/api/analyses?user=00000000-0000-0000-0000-000000000000&organization=default") \
          <(reana-client workflow list --json | jq .)
[INFO] REANA Server URL ($REANA_SERVER_URL) is: http://192.168.99.100:30376
[                                                               [
  {                                                               {
    "id": "e68c59e2-c43e-408c-82fb-dcd32836b048",             |     "Name": "epic_hodgkin",
    "organization": "default",                                |     "UUID": "e68c59e2-c43e-408c-82fb-dcd32836b048",
    "status": "created",                                      |     "User": "00000000-0000-0000-0000-000000000000",
    "user": "00000000-0000-0000-0000-000000000000"            |     "Organization": "default",
                                                              >     "Status": "created"
  }                                                               }
]                                                               ]
```

**Comment by dinosk** [comment]
@diegodelemos  Good point, thanks. 465ac43 should sync the outputs

**Pull request merged**
