### PR TITLE
cli: simplify workflow commands

### LINKED ISSUE #131: cli: simplify workflow commands
`reana-client workflow list` -> `reana-client workflows`
`reana-client workflow create` -> `reana-client new`
`reana-client workflow status` -> `reana-client status`
`reana-client workflow start` -> `reana-client run|submit|start` @reanahub/developers what's the last pick for this keyword?
`reana-client analysis validate` -> `reana-client validate`
`reana-client status` -> `reana-client ping`

### PR DESCRIPTION
**Pull request by diegodelemos**
* (Closes #131).

### CODE REVIEW

**Comment by dinosk** [comment]
:+1: After merging this we'll need to move the `reana-client workflow status` `progress` column in `reana-client status`.

**Comment by dinosk** [comment]
Actually the issue mentions moving `reana-client workflow status` to `reana-client status` and (previous) `reana-client status` to `reana-client ping`. I think this would work better because the progress is shown currently in a column and the `reana-client status` output is formatted in separate lines.

**Comment by diegodelemos** [comment]
@dinosk can you have a look to https://github.com/reanahub/reana-client/pull/139/commits/4e45ca7ad961a432c1353d476c582bb8edbcf048 regarding to our IRL discussion. If it is ok I will squash.

**Comment by dinosk** [comment]
@diegodelemos Works great :+1:

**Pull request merged**
