### PR TITLE
validate: add serial parameters validation

### LINKED ISSUE #465: validate: serial workflow parameters
The `validate` command should discover errors with parameters early. 

Take Serial workflow engine, for example `reana-demo-worldpopulation`, and simulate a typo:

```console
$ cd reana-demo-worldpopulation
$ reana-client validate 
reana.yaml is a valid REANA specification file.
$ sed -i 's,{region},{rgn},g' reana.yaml
$ reana-client validate 
reana.yaml is a valid REANA specification file.
```

That is, if the user defines a parameter `region`, but later in the job steps uses `rgn`, the current validation does not catch these types of errors.

We should check for:

- parameters defined in `inputs.parameters` specification, and if they are not used in the workflow body, emit a warning that this parameter may be unused;
- parameter placeholders used in step commands, such as `${foo}`, and if they are not defined in `inputs.parameters`, emit a warning that this parameter is not defined;

(In the second case, we could emit actually an error, however we have to be careful not to report "good" situtations, such as `${USER}` or `${REANA_WORKSPACE}` which are perfectly valid environment variables that people may want to use.  And, since these are hard to detect outside of the image environment context, we can simply emit warning for now that `rgn` seems undefined.)

### PR DESCRIPTION
**Pull request by mvidalgarcia**
closes #465

### CODE REVIEW

**Comment by audrium** [comment]
LGTM! :rocket: Just a question whether we should add some parameter docstrings to `validate.py` functions as in [this](https://github.com/reanahub/reana-client/pull/470/files#diff-4f20d18bf32c181d09b016a6a363171402d113bb01347de15da4768afcbe6998R201) example

**Comment by mvidalgarcia** [comment]
> LGTM! 🚀 Just a question whether we should add some parameter docstrings to `validate.py` functions as in [this](https://github.com/reanahub/reana-client/pull/470/files#diff-4f20d18bf32c181d09b016a6a363171402d113bb01347de15da4768afcbe6998R201) example

Docstrings added.

**Review by diegodelemos — APPROVED** [review]
Looks good to me and works fine (tested few cases):
- Case defined in original issue:
```
~/reana-demow-worldpopulation $ git diff
diff --git a/reana.yaml b/reana.yaml                                                                                                                                                                                                  
index e3db858..03a0d7f 100644                                                                                                                                                                                                         
--- a/reana.yaml                                        
+++ b/reana.yaml                                                                                                   
@@ -16,7 +16,7 @@ workflow:
     steps:                                                                                                                                                                                                                           
       - environment: 'reanahub/reana-env-jupyter:1.0.0'
         commands:
-          - mkdir -p results && papermill ${notebook} /dev/null -p input_file ${input_file} -p output_file ${output_file} -p region ${region} -p year_min ${year_min} -p year_max ${year_max}
+          - mkdir -p results && papermill ${notebook} /dev/null -p input_file ${input_file} -p output_file ${output_file} -p region ${rgn} -p year_min ${year_min} -p year_max ${year_max}
 outputs:
   files:
     - results/plot.png
~/reana-demow-worldpopulation $ reana-client create
[INFO] Creating a workflow...
==> WARNING: Input parameter "region" is not being used.
==> WARNING: Parameter "rgn" is not defined in inputs parameters.
workflow.1
```
- User referencing environment variables in their jobs:
```
~/reana-demow-worldpopulation $ git diff
diff --git a/reana.yaml b/reana.yaml
index e3db858..c2bb74c 100644
--- a/reana.yaml
+++ b/reana.yaml
@@ -16,7 +16,7 @@ workflow:
     steps:
       - environment: 'reanahub/reana-env-jupyter:1.0.0'
         commands:
-          - mkdir -p results && papermill ${notebook} /dev/null -p input_file ${input_file} -p output_file ${output_file} -p region ${region} -p year_min ${year_min} -p year_max ${year_max}
+          - $\{SHELL\} -c 'mkdir -p results && papermill ${notebook} /dev/null -p input_file ${input_file} -p output_file ${output_file} -p region ${rgn} -p year_min ${year_min} -p year_max ${year_max}'
 outputs:
   files:
     - results/plot.png
~/reana-demow-worldpopulation $ reana-client create
==> WARNING: Input parameter "region" is not being used.
==> WARNING: Parameter "rgn" is not defined in inputs parameters.
workflow.2
```
- User has a syntax error when referencing a parameter (e.g. forgetting to close `{`)
```
~/reana-demow-worldpopulation $ git diff
diff --git a/reana.yaml b/reana.yaml
index e3db858..5352992 100644
--- a/reana.yaml
+++ b/reana.yaml
@@ -16,7 +16,7 @@ workflow:
     steps:
       - environment: 'reanahub/reana-env-jupyter:1.0.0'
         commands:
-          - mkdir -p results && papermill ${notebook} /dev/null -p input_file ${input_file} -p output_file ${output_file} -p region ${region} -p year_min ${year_min} -p year_max ${year_max}
+          - mkdir -p results && papermill ${notebook} /dev/null -p input_file ${input_file} -p output_file ${output_file -p region ${rgn} -p year_min ${year_min} -p year_max ${year_max}
 outputs:
   files:
     - results/plot.png
~/reana-demow-worldpopulation $ reana-client create
==> WARNING: Input parameter "output_file" is not being used.
==> WARNING: Input parameter "region" is not being used.
==> WARNING: Parameter "output_file -p region ${rgn" is not defined in inputs parameters.
workflow.3
```


I minor comment to take into account not now but when dealing with Yadage and CWL. Should we also display in which step the error is caught? On the one hand, it is nice for big workflows. On the other hand, users can easily grep or use the editor search capabilities to look for the specific string that produces the error.

**Comment by mvidalgarcia** [comment]
> I minor comment to take into account not now but when dealing with Yadage and CWL. Should we also display in which step the error is caught? On the one hand, it is nice for big workflows. On the other hand, users can easily grep or use the editor search capabilities to look for the specific string that produces the error.

That's a very valid point that can facilitate users to identify issues. I've modified the logic to include the step(s) where the parameter was found.

**Pull request merged**
