### PR TITLE
cwl: initial integration

### PR DESCRIPTION
**Pull request by diegodelemos**
* Squashed version of https://github.com/reanahub/reana-client/pull/36

### CODE REVIEW

**Comment by tiborsimko** [comment]
@anton-khodak Are you OK with squashing the commits together? Our typical feature branch practices are:

- create logically separate commits for logically separate things 
- if a commit is working only partially, and it is repaired later by another commit, then squash them together
- if a commit implements the basic functionality fully, and another commit improves upon it or optimises some of it, then keep them separated
- there should be no explicit merge commits in feature branches

Basically, if you think that there are chances that you (or others) could start another bug fix branch or another feature branch *in the middle* of the PR commit tree,  then let's not squash.  But if you think you would now always start new feature branches or bug fixes *on top* of the PR commit tree, then let's squash the PR commit tree in order to keep the commit log history clean.  

In this concrete case at hand, since the early CWL support development was happening for an "unreleased" version of REANA, I guess the "intermediary commits" might not be useful to keep standalone and the squashing might be OK?

**P.S.** See also some old verbose musings on these practices:
http://web.archive.org/web/20150704025403/http://invenio-software.org:80/wiki/Tools/Git/Workflow#R1.Remarksoncommithistory

**Comment by anton-khodak** [comment]
Generally, I believe that squashing commits has its downsides in distorting the actual development and contribution history (which can be valuable and informative especially for long-developed feature branches), but in this case, I agree that this PR, as well as the ones in `reana-server` and `reana-workflow-controller`, can be squashed.

**Comment by diegodelemos** [comment]
@tiborsimko WIP testing the following way:
* Using `reana-cwl-runner` following https://github.com/common-workflow-language/cwltool#run-on-the-command-line
* Downloading example files from https://github.com/common-workflow-language/cwltool/tree/master/tests/wf
* Updating components accordingly with their `reana-cwl-runner` PRs: [RC](https://github.com/reanahub/reana-client/pull/68), [RS](https://github.com/reanahub/reana-server/pull/35), [RWC](https://github.com/reanahub/reana-workflow-controller/pull/67) and [RWE-CWL](https://github.com/reanahub/reana-workflow-controller/pull/67).

```console
$ # install reana-client
$ export REANA_SERVER_URL=http://192.168.99.100:31824
$ mkdir test
$ cd test
$ # input file
$ curl -O https://raw.githubusercontent.com/common-workflow-language/cwltool/master/tests/wf/whale.txt
$ # CWL spec
$ curl -O https://raw.githubusercontent.com/common-workflow-language/cwltool/master/tests/wf/wc-tool.cwl
$ # input parameters
$ curl -O https://raw.githubusercontent.com/common-workflow-language/cwltool/master/tests/wf/wc-job.json
$ # run REANA cwl runner
$ reana-cwl-runner wc-tool.cwl wc-job.json
$ reana-client workflow list
Name          |UUID                                |User                                |Organization|Status
--------------|------------------------------------|------------------------------------|------------|--------
wizardly_curie|1b3c47ba-9752-413a-b32e-d947b3f715e7|00000000-0000-0000-0000-000000000000|default     |finished
# currently reana-client writes to `./outputs` so we create it.
$ mkdir outputs
$ reana-client outputs download output --workflow 1b3c47ba-9752-413a-b32e-d947b3f715e7
[INFO] output binary file downloaded ... writing to ./outputs/
$ cat outputs/output
16
```

Still having:
```console
....
jsonschema.exceptions.ValidationError: None is not of type 'string'

Failed validating 'type' in schema['properties']['user']:
    {'type': 'string'}

On instance['user']:
    None
```

**Comment by tiborsimko** [comment]
Confirm this works with:
- reana-server @ pr/35
- reana-workflow-controller @ pr/67
- reana-workflow-engine-cwl @ pr/5
- reana-client @ pr/68
- all the other components @ 0.1.0  

... and seeing the same lots of jsonschema validation errors when running the full CWL test suite with `run_test.sh RUNNER=reana-cwl-runner`.

**Comment by diegodelemos** [comment]
@tiborsimko `jsonschema` response validation fixed https://github.com/reanahub/reana-workflow-controller/pull/67/commits/52f4c57345141451fb387aed93c9289bf24f4563

**Pull request merged**
